"""Keyword/regex rules for transaction categorization."""

# Each rule: (regex_pattern, category_id, category_name)
# Patterns are matched against UPPERCASED description
KEYWORD_RULES: list[tuple[str, int, str]] = [
    # Groceries
    (r"GROCERY|GROCER|SUPERMARKET|KIRANA|PROVISION|VEGETABLE|FRUIT", 1, "Groceries"),
    (r"BIGBASKET|BLINKIT|ZEPTO|JIOMART|INSTAMART|DMART|GROFERS", 1, "Groceries"),
    # Transportation
    (r"UBER|OLA|RAPIDO|CAB|TAXI|AUTO|RIDE|METRO|RAIL|BUS|FUEL|PETROL|DIESEL|CNG", 2, "Transportation"),
    (r"IRCTC|RAILWAY|PARKING|TOLL", 2, "Transportation"),
    # Utilities
    (r"ELECTRICITY|ELECTRIC|POWER|WATER|GAS|BROADBAND|WIFI|FIBER|INTERNET|MOBILE.*RECHARGE", 3, "Utilities"),
    (r"BSES|TATA POWER|ADANI|JAL BOARD|AIRTEL|JIO|VODAFONE|BSNL|ACT FIBER", 3, "Utilities"),
    # Entertainment
    (r"NETFLIX|PRIME.*VIDEO|DISNEY|HOTSTAR|SPOTIFY|YOUTUBE|MOVIE|CINEMA|THEATRE|CONCERT|GAME", 4, "Entertainment"),
    (r"PVR|INOX|BOOKMYSHOW|STEAM|PLAYSTATION|XBOX", 4, "Entertainment"),
    # Healthcare
    (r"HOSPITAL|CLINIC|DOCTOR|PHARMACY|MEDICINE|MEDICAL|HEALTH|DIAGNOSTIC|LAB|TEST|PATHOLOG", 5, "Healthcare"),
    (r"APOLLO|MEDPLUS|PHARMEASY|NETMEDS|1MG|PRACTO|FORTIS|MAX HOSP", 5, "Healthcare"),
    # Dining
    (r"SWIGGY|ZOMATO|RESTAURANT|CAFE|COFFEE|FOOD|PIZZA|BURGER|CHICKEN|BIRYANI|DINE|LUNCH|DINNER|BREAKFAST", 6, "Dining"),
    (r"DOMINO|KFC|MCDONALD|SUBWAY|STARBUCKS|CHAAYOS|HALDIRAM", 6, "Dining"),
    # Shopping
    (r"AMAZON|FLIPKART|MYNTRA|AJIO|MEESHO|NYKAA|PURCHASE|ORDER|SHOPPING|STORE|MALL", 7, "Shopping"),
    (r"CROMA|RELIANCE DIGITAL|VIJAY SALES|IKEA|H&M|ZARA", 7, "Shopping"),
    # Education
    (r"COURSE|TUITION|SCHOOL|COLLEGE|UNIVERSITY|EDUCATION|TRAINING|WORKSHOP|CERTIFICATION|EXAM", 8, "Education"),
    (r"COURSERA|UDEMY|UNACADEMY|BYJU|SKILLSHARE|LINKEDIN LEARN", 8, "Education"),
    # Travel
    (r"HOTEL|FLIGHT|AIRLINE|AIRPORT|BOOKING|TRAVEL|TRIP|VACATION|RESORT|HOSTEL", 9, "Travel"),
    (r"MAKEMYTRIP|GOIBIBO|CLEARTRIP|YATRA|OYO|AIRBNB|INDIGO|AIR INDIA|SPICEJET|VISTARA", 9, "Travel"),
    # Investments
    (r"MUTUAL FUND|SIP|STOCK|SHARE|INVEST|DEMAT|TRADING|DIVIDEND|BOND|FD|FIXED DEPOSIT", 10, "Investments"),
    (r"ZERODHA|GROWW|UPSTOX|ANGEL ONE|KUVERA|ET MONEY", 10, "Investments"),
    # Rent/Housing
    (r"RENT|HOUSE RENT|FLAT RENT|PG|PAYING GUEST|MAINTENANCE|SOCIETY|EMI.*HOME|HOME.*LOAN", 11, "Rent/Housing"),
    # Insurance
    (r"INSURANCE|PREMIUM|LIC|POLICY|HEALTH.*COVER|TERM.*PLAN|LIFE.*COVER", 12, "Insurance"),
    (r"POLICYBAZAAR|BAJAJ ALLIANZ|HDFC LIFE|ICICI PRUDENTIAL|STAR HEALTH", 12, "Insurance"),
    # Personal Care
    (r"SALON|HAIRCUT|SPA|MASSAGE|BEAUTY|PARLOUR|PARLOR|GROOMING", 13, "Personal Care"),
    (r"URBAN COMPANY|LAKME|JAWED HABIB|NATURALS", 13, "Personal Care"),
    # Subscriptions
    (r"SUBSCRIPTION|MEMBERSHIP|ANNUAL.*PLAN|MONTHLY.*PLAN|RENEWAL", 14, "Subscriptions"),
    (r"APPLE.*STORE|GOOGLE.*PLAY|MICROSOFT.*365|ADOBE|NOTION|SLACK", 14, "Subscriptions"),
]
