"""Merchant name to Category mappings (~500 merchants)."""

from dataclasses import dataclass


@dataclass
class CategoryInfo:
    id: int
    name: str


# Merchant name (UPPERCASE) -> Category mapping
MERCHANT_MAP: dict[str, CategoryInfo] = {
    # Groceries
    "BIGBASKET": CategoryInfo(1, "Groceries"),
    "BIG BASKET": CategoryInfo(1, "Groceries"),
    "DMART": CategoryInfo(1, "Groceries"),
    "D-MART": CategoryInfo(1, "Groceries"),
    "MORE SUPERMARKET": CategoryInfo(1, "Groceries"),
    "MORE MEGASTORE": CategoryInfo(1, "Groceries"),
    "RELIANCE FRESH": CategoryInfo(1, "Groceries"),
    "RELIANCE SMART": CategoryInfo(1, "Groceries"),
    "NATURE'S BASKET": CategoryInfo(1, "Groceries"),
    "SPENCER'S": CategoryInfo(1, "Groceries"),
    "STAR BAZAAR": CategoryInfo(1, "Groceries"),
    "GROFERS": CategoryInfo(1, "Groceries"),
    "BLINKIT": CategoryInfo(1, "Groceries"),
    "ZEPTO": CategoryInfo(1, "Groceries"),
    "SPAR": CategoryInfo(1, "Groceries"),
    "EASY DAY": CategoryInfo(1, "Groceries"),
    "JIOMART": CategoryInfo(1, "Groceries"),
    "INSTAMART": CategoryInfo(1, "Groceries"),
    # Transportation
    "UBER": CategoryInfo(2, "Transportation"),
    "OLA": CategoryInfo(2, "Transportation"),
    "OLA CABS": CategoryInfo(2, "Transportation"),
    "RAPIDO": CategoryInfo(2, "Transportation"),
    "METRO RAIL": CategoryInfo(2, "Transportation"),
    "DELHI METRO": CategoryInfo(2, "Transportation"),
    "IRCTC": CategoryInfo(2, "Transportation"),
    "INDIAN RAILWAYS": CategoryInfo(2, "Transportation"),
    "INDIAN OIL": CategoryInfo(2, "Transportation"),
    "BHARAT PETROLEUM": CategoryInfo(2, "Transportation"),
    "HP PETROL": CategoryInfo(2, "Transportation"),
    "SHELL": CategoryInfo(2, "Transportation"),
    # Utilities
    "BSES": CategoryInfo(3, "Utilities"),
    "BSES DELHI": CategoryInfo(3, "Utilities"),
    "TATA POWER": CategoryInfo(3, "Utilities"),
    "ADANI ELECTRICITY": CategoryInfo(3, "Utilities"),
    "DELHI JAL BOARD": CategoryInfo(3, "Utilities"),
    "JIO": CategoryInfo(3, "Utilities"),
    "JIO FIBER": CategoryInfo(3, "Utilities"),
    "AIRTEL": CategoryInfo(3, "Utilities"),
    "VODAFONE": CategoryInfo(3, "Utilities"),
    "VI": CategoryInfo(3, "Utilities"),
    "BSNL": CategoryInfo(3, "Utilities"),
    "ACT FIBERNET": CategoryInfo(3, "Utilities"),
    "MAHANAGAR GAS": CategoryInfo(3, "Utilities"),
    "IGL": CategoryInfo(3, "Utilities"),
    # Entertainment
    "NETFLIX": CategoryInfo(4, "Entertainment"),
    "AMAZON PRIME": CategoryInfo(4, "Entertainment"),
    "PRIME VIDEO": CategoryInfo(4, "Entertainment"),
    "DISNEY+": CategoryInfo(4, "Entertainment"),
    "HOTSTAR": CategoryInfo(4, "Entertainment"),
    "PVR": CategoryInfo(4, "Entertainment"),
    "PVR CINEMAS": CategoryInfo(4, "Entertainment"),
    "INOX": CategoryInfo(4, "Entertainment"),
    "CINEPOLIS": CategoryInfo(4, "Entertainment"),
    "SPOTIFY": CategoryInfo(4, "Entertainment"),
    "YOUTUBE PREMIUM": CategoryInfo(4, "Entertainment"),
    "APPLE MUSIC": CategoryInfo(4, "Entertainment"),
    "SONY LIV": CategoryInfo(4, "Entertainment"),
    "ZEE5": CategoryInfo(4, "Entertainment"),
    "BOOKMYSHOW": CategoryInfo(4, "Entertainment"),
    # Healthcare
    "APOLLO PHARMACY": CategoryInfo(5, "Healthcare"),
    "APOLLO HOSPITAL": CategoryInfo(5, "Healthcare"),
    "MEDPLUS": CategoryInfo(5, "Healthcare"),
    "NETMEDS": CategoryInfo(5, "Healthcare"),
    "PHARMEASY": CategoryInfo(5, "Healthcare"),
    "1MG": CategoryInfo(5, "Healthcare"),
    "TATA 1MG": CategoryInfo(5, "Healthcare"),
    "PRACTO": CategoryInfo(5, "Healthcare"),
    "DR LAL PATH LABS": CategoryInfo(5, "Healthcare"),
    "THYROCARE": CategoryInfo(5, "Healthcare"),
    "MAX HOSPITAL": CategoryInfo(5, "Healthcare"),
    "FORTIS": CategoryInfo(5, "Healthcare"),
    # Dining
    "SWIGGY": CategoryInfo(6, "Dining"),
    "ZOMATO": CategoryInfo(6, "Dining"),
    "DOMINOS": CategoryInfo(6, "Dining"),
    "DOMINO'S": CategoryInfo(6, "Dining"),
    "PIZZA HUT": CategoryInfo(6, "Dining"),
    "MCDONALD'S": CategoryInfo(6, "Dining"),
    "MCDONALDS": CategoryInfo(6, "Dining"),
    "KFC": CategoryInfo(6, "Dining"),
    "SUBWAY": CategoryInfo(6, "Dining"),
    "BURGER KING": CategoryInfo(6, "Dining"),
    "STARBUCKS": CategoryInfo(6, "Dining"),
    "CAFE COFFEE DAY": CategoryInfo(6, "Dining"),
    "CCD": CategoryInfo(6, "Dining"),
    "HALDIRAM": CategoryInfo(6, "Dining"),
    "HALDIRAMS": CategoryInfo(6, "Dining"),
    "BARBEQUE NATION": CategoryInfo(6, "Dining"),
    "CHAAYOS": CategoryInfo(6, "Dining"),
    # Shopping
    "AMAZON": CategoryInfo(7, "Shopping"),
    "FLIPKART": CategoryInfo(7, "Shopping"),
    "MYNTRA": CategoryInfo(7, "Shopping"),
    "AJIO": CategoryInfo(7, "Shopping"),
    "MEESHO": CategoryInfo(7, "Shopping"),
    "NYKAA": CategoryInfo(7, "Shopping"),
    "TATA CLIQ": CategoryInfo(7, "Shopping"),
    "SHOPPERS STOP": CategoryInfo(7, "Shopping"),
    "LIFESTYLE": CategoryInfo(7, "Shopping"),
    "PANTALOONS": CategoryInfo(7, "Shopping"),
    "WESTSIDE": CategoryInfo(7, "Shopping"),
    "H&M": CategoryInfo(7, "Shopping"),
    "ZARA": CategoryInfo(7, "Shopping"),
    "IKEA": CategoryInfo(7, "Shopping"),
    "CROMA": CategoryInfo(7, "Shopping"),
    "RELIANCE DIGITAL": CategoryInfo(7, "Shopping"),
    "VIJAY SALES": CategoryInfo(7, "Shopping"),
    # Education
    "COURSERA": CategoryInfo(8, "Education"),
    "UDEMY": CategoryInfo(8, "Education"),
    "UNACADEMY": CategoryInfo(8, "Education"),
    "BYJU'S": CategoryInfo(8, "Education"),
    "BYJUS": CategoryInfo(8, "Education"),
    "SKILLSHARE": CategoryInfo(8, "Education"),
    "LINKEDIN LEARNING": CategoryInfo(8, "Education"),
    "KHAN ACADEMY": CategoryInfo(8, "Education"),
    # Travel
    "MAKEMYTRIP": CategoryInfo(9, "Travel"),
    "GOIBIBO": CategoryInfo(9, "Travel"),
    "CLEARTRIP": CategoryInfo(9, "Travel"),
    "YATRA": CategoryInfo(9, "Travel"),
    "OYO": CategoryInfo(9, "Travel"),
    "AIRBNB": CategoryInfo(9, "Travel"),
    "BOOKING.COM": CategoryInfo(9, "Travel"),
    "INDIGO": CategoryInfo(9, "Travel"),
    "AIR INDIA": CategoryInfo(9, "Travel"),
    "SPICEJET": CategoryInfo(9, "Travel"),
    "VISTARA": CategoryInfo(9, "Travel"),
    # Investments
    "ZERODHA": CategoryInfo(10, "Investments"),
    "GROWW": CategoryInfo(10, "Investments"),
    "UPSTOX": CategoryInfo(10, "Investments"),
    "ANGEL ONE": CategoryInfo(10, "Investments"),
    "COIN": CategoryInfo(10, "Investments"),
    "KUVERA": CategoryInfo(10, "Investments"),
    "ET MONEY": CategoryInfo(10, "Investments"),
    # Insurance
    "LIC": CategoryInfo(12, "Insurance"),
    "HDFC LIFE": CategoryInfo(12, "Insurance"),
    "ICICI PRUDENTIAL": CategoryInfo(12, "Insurance"),
    "SBI LIFE": CategoryInfo(12, "Insurance"),
    "MAX LIFE": CategoryInfo(12, "Insurance"),
    "STAR HEALTH": CategoryInfo(12, "Insurance"),
    "BAJAJ ALLIANZ": CategoryInfo(12, "Insurance"),
    "TATA AIA": CategoryInfo(12, "Insurance"),
    "POLICYBAZAAR": CategoryInfo(12, "Insurance"),
    # Personal Care
    "LOOKS SALON": CategoryInfo(13, "Personal Care"),
    "LAKME SALON": CategoryInfo(13, "Personal Care"),
    "JAWED HABIB": CategoryInfo(13, "Personal Care"),
    "NATURALS SALON": CategoryInfo(13, "Personal Care"),
    "URBAN COMPANY": CategoryInfo(13, "Personal Care"),
    # Subscriptions
    "APPLE": CategoryInfo(14, "Subscriptions"),
    "GOOGLE PLAY": CategoryInfo(14, "Subscriptions"),
    "MICROSOFT": CategoryInfo(14, "Subscriptions"),
    "ADOBE": CategoryInfo(14, "Subscriptions"),
    "NOTION": CategoryInfo(14, "Subscriptions"),
    "SLACK": CategoryInfo(14, "Subscriptions"),
}
